typography_spectrum: 0.14248012634925544
color:
  brandStrength: 0.8723603002727032
  lightness: 0.6941347178071737
  saturation: 0.26533284853212535
  rhythmicContrast: 0.9074061580467969
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.4164780762512237
author:
  name: Kleerkut Teknologies Inc
  email: bundyszabo@gmail.com
  url: HouseShmas.com
name: HouseShams.com
title: Shame on Them? or Fame?
description: Court of Public Opinion
